// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://krxgiqgdsuyiuvolprjd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtyeGdpcWdkc3V5aXV2b2xwcmpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5ODg1MTYsImV4cCI6MjA3MzU2NDUxNn0.XojJUl5kAqDfvgRY6bTIIwFv2bY2Ebnr7x5sxCyRNwQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});